FROM python:2.7.12

# Create app directory
RUN mkdir -p /home/src
WORKDIR /home/src

# Install app dependencies
COPY requirements.txt /home/src/
RUN pip install -r requirements.txt

# Bundle app source
COPY . /home/src/

CMD ["rqworker","-c", "conf_dev"]