export const REQUEST_LYRICS = 'REQUEST_LYRICS';
export const REQUEST_LYRICS_SUCCESS = 'REQUEST_LYRICS_SUCCESS';
export const REQUEST_LYRICS_ERROR = 'REQUEST_LYRICS_ERROR';
export const INIT_SOCKET = 'INIT_SOCKET';
export const SOCKET_ID = 'SOCKET_ID';
export const SOCKET_LYRIKS = 'SOCKET_LYRIKS';
export const IRON_CALLED = 'IRON_CALLED';